# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='dojosecrets.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='secrets',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='secrets',
            name='user_id',
        ),
    ]
