# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0002_auto_20170322_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secrets',
            old_name='secret',
            new_name='secret_text',
        ),
    ]
