# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0003_auto_20170322_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrets',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_secrets', to='dojosecrets.Users'),
            preserve_default=False,
        ),
    ]
