# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0004_secrets_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='secret_likes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secret_likes', to='dojosecrets.Secrets'),
            preserve_default=False,
        ),
    ]
